stages:
  - build

build:
  stage: build
  image: node
  script:
    - echo "[INFO] YML Settings"
    - cp -R front /home/ubuntu/front
    - cd /home/ubuntu/front
    - sh ./front.sh
  tags:
    - build
