stages:
  - build

build:
  stage: build
  image: gradle:6.9.3-jdk17
  before_script:
    - echo "[INFO] YML Settings"
    - chmod +x backend/gradlew
    - cd backend
  script:
    - ./gradlew clean build -x test
    - cp build/libs/backend-0.0.1-SNAPSHOT.jar /home/ubuntu/back
    - cd /home/ubuntu/back
    - sh back.sh
  only:
    - /.*\/master$/  
  tags:
    - build