tests:
  - id: 1
    description: "1. Random Forest Regression"
    endpoint: "/predict"
    method: "POST"
    payload:
      file_path: "https://s3.ap-northeast-2.amazonaws.com/wadada-bucket/304efd3f-416c-46e8-891a-a92d85afab85.csv"
      model_choice: "random_forest_regression"
      target_variable: "PerfScoreID"
      feature_columns:
        - "EmpSatisfaction"
        - "EngagementSurvey"
        - "SpecialProjectsCount"
        - "Absences"
        - "DaysLateLast30"
        - "Department"
        - "Position"
        - "Salary"
        - "TenureDays"
        - "ManagerID"
      id_column: "EmpID"
    expected_status: 200

  - id: 2
    description: "2. Random Forest Classification"
    endpoint: "/predict"
    method: "POST"
    payload:
      file_path: "https://s3.ap-northeast-2.amazonaws.com/wadada-bucket/304efd3f-416c-46e8-891a-a92d85afab85.csv"
      model_choice: "random_forest_classification"
      target_variable: "Termd"
      feature_columns:
        - "EmpSatisfaction"
        - "EngagementSurvey"
        - "PerfScoreID"
        - "Salary"
        - "TenureDays"
        - "Absences"
        - "DaysLateLast30"
        - "Department"
        - "Position"
        - "ManagerID"
      id_column: "EmpID"
    expected_status: 200

  - id: 3
    description: "3. Logistic Regression Binary Classification - Generate Overpaid Feature"
    endpoint: "/predict"
    method: "POST"
    payload:
      file_path: "https://s3.ap-northeast-2.amazonaws.com/wadada-bucket/304efd3f-416c-46e8-891a-a92d85afab85.csv"
      model_choice: "logistic_regression_binary"
      target_variable: "Overpaid"
      feature_columns:
        - "PerfScoreID"
        - "EmpSatisfaction"
        - "EngagementSurvey"
        - "SpecialProjectsCount"
        - "Absences"
        - "DaysLateLast30"
        - "Department"
        - "Position"
        - "Salary"
        - "TenureDays"
        - "ManagerID"
      binary_conditions:
        - column: "Salary"
          operator: ">"
          value: 75000
          target_column: "Overpaid"
        - column: "PerfScoreID"
          operator: "<"
          value: 3
          target_column: "Overpaid"
    expected_status: 200

  - id: 4
    description: "4. Logistic Regression Multinomial Classification"
    endpoint: "/predict"
    method: "POST"
    payload:
      file_path: "https://s3.ap-northeast-2.amazonaws.com/wadada-bucket/304efd3f-416c-46e8-891a-a92d85afab85.csv"
      model_choice: "logistic_regression_multinomial"
      target_variable: "PerfScoreID"
      feature_columns:
        - "EmpSatisfaction"
        - "EngagementSurvey"
        - "SpecialProjectsCount"
        - "Absences"
        - "DaysLateLast30"
        - "Department"
        - "Position"
        - "Salary"
        - "TenureDays"
        - "ManagerID"
      plot_filename: "multinomial_plot.png"
    expected_status: 200

  - id: 5
    description: "5. K-Means Clustering - Employee Segmentation"
    endpoint: "/predict"
    method: "POST"
    payload:
      file_path: "https://s3.ap-northeast-2.amazonaws.com/wadada-bucket/304efd3f-416c-46e8-891a-a92d85afab85.csv"
      model_choice: "kmeans_clustering_segmentation"
      feature_columns:
        - "Position"
        - "Department"
        - "Salary"
        - "TenureDays"
        - "ManagerID"
      num_clusters: 4
    expected_status: 200

  - id: 6
    description: "6. K-Means Clustering - Anomaly Detection"
    endpoint: "/predict"
    method: "POST"
    payload:
      file_path: "https://s3.ap-northeast-2.amazonaws.com/wadada-bucket/304efd3f-416c-46e8-891a-a92d85afab85.csv"
      model_choice: "kmeans_clustering_anomaly_detection"
      feature_columns:
        - "Salary"
        - "TenureDays"
        - "Absences"
        - "EngagementSurvey"
        - "ManagerID"
      num_clusters: 4
      threshold: 1.5
    expected_status: 200

  - id: 7
    description: "7. Neural Network Regression"
    endpoint: "/predict"
    method: "POST"
    payload:
      file_path: "https://s3.ap-northeast-2.amazonaws.com/wadada-bucket/304efd3f-416c-46e8-891a-a92d85afab85.csv"
      model_choice: "neural_network_regression"
      target_variable: "Termd" # Example target variable; adjust as needed
      feature_columns:
        - "MarriedID"
        - "MaritalStatusID"
        - "GenderID"
        - "EmpStatusID"
        - "DeptID"
        - "PerfScoreID"
        - "FromDiversityJobFairID"
        - "Salary"
        - "Termd" # Typically, target variable should not be in features; ensure correct usage
        - "PositionID"
        - "State"
        - "Zip"
        - "DOB"
        - "Sex"
        - "MaritalDesc"
        - "CitizenDesc"
        - "HispanicLatino"
        - "RaceDesc"
        - "DateofHire"
        - "DateofTermination"
        - "TermReason"
        - "EmploymentStatus"
        - "Department"
        - "ManagerName"
        - "ManagerID"
        - "RecruitmentSource"
        - "PerformanceScore"
        - "EngagementSurvey"
        - "EmpSatisfaction"
        - "SpecialProjectsCount"
        - "LastPerformanceReview_Date"
        - "DaysLateLast30"
        - "Absences"
        - "TenureDays"
      id_column: "EmpID"
    expected_status: 200

  - id: 8
    description: "8. Graph Neural Network Analysis"
    endpoint: "/predict"
    method: "POST"
    payload:
      file_path: "https://s3.ap-northeast-2.amazonaws.com/wadada-bucket/304efd3f-416c-46e8-891a-a92d85afab85.csv"
      model_choice: "graph_neural_network_analysis"
      id_column: "EmpID"
      additional_features:
        - "MarriedID"
        - "MaritalStatusID"
        - "GenderID"
        - "EmpStatusID"
        - "DeptID"
        - "PerfScoreID"
        - "FromDiversityJobFairID"
        - "Salary"
        - "Termd"
        - "PositionID"
        - "State"
        - "Zip"
        - "DOB"
        - "Sex"
        - "MaritalDesc"
        - "CitizenDesc"
        - "HispanicLatino"
        - "RaceDesc"
        - "DateofHire"
        - "DateofTermination"
        - "TermReason"
        - "EmploymentStatus"
        - "Department"
        - "ManagerName"
        - "ManagerID"
        - "RecruitmentSource"
        - "PerformanceScore"
        - "EngagementSurvey"
        - "EmpSatisfaction"
        - "SpecialProjectsCount"
        - "LastPerformanceReview_Date"
        - "DaysLateLast30"
        - "Absences"
        - "TenureDays"
      feature_generations:
        - type: "period"
          new_column: "TenureDays"
          start_column: "DateofHire"
          end_column: "DateofTermination"
      exclude_columns:
        - "DOB" # Example: exclude Date of Birth if not needed
      task_type: "classification" # or "regression" based on your requirement
      relationship_column: "ManagerID" # Specify the column used for edge creation
      create_random_edges: false
      sample_size: 10
      random_state: 42
    expected_status: 200
