tests:
  - id: 1
    description: "1. Random Forest Regression"
    endpoint: "/predict"
    method: "POST"
    payload:
      file_path: "https://s3.ap-northeast-2.amazonaws.com/wadada-bucket/304efd3f-416c-46e8-891a-a92d85afab85.csv"
      model_choice: "random_forest_regression"
      target_variable: "PerfScoreID"
      feature_columns:
        - "EmpSatisfaction"
        - "EngagementSurvey"
        - "SpecialProjectsCount"
        - "Absences"
        - "DaysLateLast30"
        - "Department"
        - "Position"
        - "Salary"
        - "TenureDays"
        - "ManagerID"
      id_column: "EmpID"
    expected_status: 200

  - id: 2
    description: "2. Random Forest Classification"
    endpoint: "/predict"
    method: "POST"
    payload:
      file_path: "https://s3.ap-northeast-2.amazonaws.com/wadada-bucket/304efd3f-416c-46e8-891a-a92d85afab85.csv"
      model_choice: "random_forest_classification"
      target_variable: "Termd"
      feature_columns:
        - "EmpSatisfaction"
        - "EngagementSurvey"
        - "PerfScoreID"
        - "Salary"
        - "TenureDays"
        - "Absences"
        - "DaysLateLast30"
        - "Department"
        - "Position"
        - "ManagerID"
      id_column: "EmpID"
    expected_status: 200

  - id: 3
    description: "3. Logistic Regression Binary Classification - Generate Overpaid Feature"
    endpoint: "/predict"
    method: "POST"
    payload:
      file_path: "https://s3.ap-northeast-2.amazonaws.com/wadada-bucket/304efd3f-416c-46e8-891a-a92d85afab85.csv"
      model_choice: "logistic_regression_binary"
      target_variable: "Overpaid"
      feature_columns:
        - "PerfScoreID"
        - "EmpSatisfaction"
        - "EngagementSurvey"
        - "SpecialProjectsCount"
        - "Absences"
        - "DaysLateLast30"
        - "Department"
        - "Position"
        - "Salary"
        - "TenureDays"
        - "ManagerID"
      binary_conditions:
        - column: "Salary"
          operator: ">"
          value: 75000
          target_column: "Overpaid"
        - column: "PerfScoreID"
          operator: "<"
          value: 3
          target_column: "Overpaid"
    expected_status: 200

  - id: 4
    description: "4. Logistic Regression Multinomial Classification"
    endpoint: "/predict"
    method: "POST"
    payload:
      file_path: "https://s3.ap-northeast-2.amazonaws.com/wadada-bucket/304efd3f-416c-46e8-891a-a92d85afab85.csv"
      model_choice: "logistic_regression_multinomial"
      target_variable: "PerfScoreID"
      feature_columns:
        - "EmpSatisfaction"
        - "EngagementSurvey"
        - "SpecialProjectsCount"
        - "Absences"
        - "DaysLateLast30"
        - "Department"
        - "Position"
        - "Salary"
        - "TenureDays"
        - "ManagerID"
      plot_filename: "multinomial_plot.png"
    expected_status: 200

  - id: 5
    description: "5. K-Means Clustering - Employee Segmentation"
    endpoint: "/predict"
    method: "POST"
    payload:
      file_path: "https://s3.ap-northeast-2.amazonaws.com/wadada-bucket/304efd3f-416c-46e8-891a-a92d85afab85.csv"
      model_choice: "kmeans_clustering_segmentation"
      feature_columns:
        - "Position"
        - "Department"
        - "Salary"
        - "TenureDays"
        - "ManagerID"
      num_clusters: 4
    expected_status: 200

  - id: 6
    description: "6. K-Means Clustering - Anomaly Detection"
    endpoint: "/predict"
    method: "POST"
    payload:
      file_path: "https://s3.ap-northeast-2.amazonaws.com/wadada-bucket/304efd3f-416c-46e8-891a-a92d85afab85.csv"
      model_choice: "kmeans_clustering_anomaly_detection"
      feature_columns:
        - "Salary"
        - "TenureDays"
        - "Absences"
        - "EngagementSurvey"
        - "ManagerID"
      num_clusters: 4
      threshold: 1.5
    expected_status: 200

  - id: 7
    description: "Neural Network Regression on Absence Cost Impact"
    endpoint: "/predict"
    method: "POST"
    payload:
      file_path: "./dataset/Simulated_Factory_Impact_Data.csv"
      model_choice: "neural_network_regression"
      target_variable: "Absence Cost Impact ($)"
      feature_columns:
        - "Factory Operating Rate (%)"
        - "Production Volume (units)"
        - "Production Efficiency (%)"
        - "Production Downtime Rate (%)"
        - "Role Criticality Score"
        - "Absence Impact on Volume (units)"
        - "Absence Impact on Efficiency (%)"
        - "Overtime Dependency Rate (%)"
        - "Maintenance Requirement Increase"
        - "Cross-Training Index"
        - "Error Rate Increase (%)"
        - "Process Bottleneck Potential (%)"
        - "Team Coordination Score"
        - "Job Role Coverage (%)"
        - "Absenteeism Frequency"
        - "Shift Flexibility Score"
        - "Operational Risk Factor"
        - "Skill Redundancy Level"
      id_column: "Employee ID"
    expected_status: 200

  - id: 8
    description: "Graph Neural Network Regression on Absence Cost Impact"
    endpoint: "/predict"
    method: "POST"
    payload:
      file_path: "./dataset/Simulated_Factory_Impact_Data.csv"
      model_choice: "graph_neural_network_analysis"
      id_column: "Employee ID"
      additional_features:
        - "Factory Operating Rate (%)"
        - "Production Volume (units)"
        - "Production Efficiency (%)"
        - "Production Downtime Rate (%)"
        - "Role Criticality Score"
        - "Absence Impact on Volume (units)"
        - "Absence Impact on Efficiency (%)"
        - "Overtime Dependency Rate (%)"
        - "Maintenance Requirement Increase"
        - "Cross-Training Index"
        - "Error Rate Increase (%)"
        - "Process Bottleneck Potential (%)"
        - "Team Coordination Score"
        - "Job Role Coverage (%)"
        - "Absenteeism Frequency"
        - "Shift Flexibility Score"
        - "Operational Risk Factor"
        - "Skill Redundancy Level"
      target_column: "Absence Cost Impact ($)"
      task_type: "regression"
      relationship_column: "ManagerID" # Adjust if 'ManagerID' exists in your dataset
      sample_size: 10
      random_state: 42
    expected_status: 200

  - id: 9
    description: "Graph Neural Network Classification on Role Criticality Score"
    endpoint: "/predict"
    method: "POST"
    payload:
      file_path: "./dataset/Simulated_Factory_Impact_Data.csv"
      model_choice: "graph_neural_network_analysis"
      id_column: "Employee ID"
      additional_features:
        - "Factory Operating Rate (%)"
        - "Production Volume (units)"
        - "Production Efficiency (%)"
        - "Production Downtime Rate (%)"
        - "Absence Impact on Volume (units)"
        - "Absence Impact on Efficiency (%)"
        - "Overtime Dependency Rate (%)"
        - "Maintenance Requirement Increase"
        - "Cross-Training Index"
        - "Error Rate Increase (%)"
        - "Process Bottleneck Potential (%)"
        - "Team Coordination Score"
        - "Job Role Coverage (%)"
        - "Absenteeism Frequency"
        - "Shift Flexibility Score"
        - "Operational Risk Factor"
        - "Skill Redundancy Level"
      target_column: "Role Criticality Score"
      task_type: "classification"
      relationship_column: "ManagerID" # Adjust if 'ManagerID' exists in your dataset
      sample_size: 10
      random_state: 42
    expected_status: 200

  - id: 10
    description: "Neural Network Regression with Limited Features"
    endpoint: "/predict"
    method: "POST"
    payload:
      file_path: "./dataset/Simulated_Factory_Impact_Data.csv"
      model_choice: "neural_network_regression"
      target_variable: "Absence Cost Impact ($)"
      feature_columns:
        - "Production Volume (units)"
        - "Overtime Dependency Rate (%)"
        - "Shift Flexibility Score"
        - "Absenteeism Frequency"
      id_column: "Employee ID"
    expected_status: 200

  - id: 11
    description: "Neural Network Regression with Missing Values"
    endpoint: "/predict"
    method: "POST"
    payload:
      file_path: "./dataset/Simulated_Factory_Impact_Data.csv"
      model_choice: "neural_network_regression"
      target_variable: "Absence Cost Impact ($)"
      feature_columns:
        - "Factory Operating Rate (%)"
        - "Production Volume (units)"
        - "Production Efficiency (%)"
        - "Production Downtime Rate (%)"
        - "Role Criticality Score"
        - "Absence Impact on Volume (units)"
        - "Absence Impact on Efficiency (%)"
        - "Overtime Dependency Rate (%)"
        - "Maintenance Requirement Increase"
        - "Cross-Training Index"
        - "Error Rate Increase (%)"
        - "Process Bottleneck Potential (%)"
        - "Team Coordination Score"
        - "Job Role Coverage (%)"
        - "Absenteeism Frequency"
        - "Shift Flexibility Score"
        - "Operational Risk Factor"
        - "Skill Redundancy Level"
      id_column: "Employee ID"
    expected_status: 200

  - id: 12
    description: "12. Support Vector Machine Classification"
    endpoint: "/predict"
    method: "POST"
    payload:
      file_path: "https://s3.ap-northeast-2.amazonaws.com/wadada-bucket/304efd3f-416c-46e8-891a-a92d85afab85.csv"
      model_choice: "support_vector_machine_classification"
      target_variable: "Termd"
      feature_columns:
        - "EmpSatisfaction"
        - "EngagementSurvey"
        - "PerfScoreID"
        - "Salary"
        - "TenureDays"
        - "Absences"
        - "DaysLateLast30"
      id_column: "EmpID"
      kernel: "rbf"
      C: 1.0
      gamma: "scale"
    expected_status: 200

  - id: 13
    description: "13. Support Vector Machine Regression with Hyperparameter Tuning"
    endpoint: "/predict"
    method: "POST"
    payload:
      file_path: "./dataset/Simulated_Factory_Impact_Data.csv"
      model_choice: "support_vector_machine_regression"
      target_variable: "Absence Cost Impact ($)"
      feature_columns:
        - "Factory Operating Rate (%)"
        - "Production Volume (units)"
        - "Production Efficiency (%)"
        - "Production Downtime Rate (%)"
        - "Role Criticality Score"
        - "Absence Impact on Volume (units)"
        - "Absence Impact on Efficiency (%)"
        - "Overtime Dependency Rate (%)"
        - "Maintenance Requirement Increase"
        - "Cross-Training Index"
        - "Error Rate Increase (%)"
        - "Process Bottleneck Potential (%)"
        - "Team Coordination Score"
        - "Job Role Coverage (%)"
        - "Absenteeism Frequency"
        - "Shift Flexibility Score"
        - "Operational Risk Factor"
        - "Skill Redundancy Level"
      id_column: "Employee ID"
      param_grid:
        C: [0.1, 1, 10]
        gamma: ["scale", "auto"]
        epsilon: [0.1, 0.2]
        kernel: ["rbf", "linear"]
    expected_status: 200
